### ISSUE TITLE
Is there any possible to capture partial area by user choose

### ISSUE THREAD

**Issue by wfg2513148** [Dani3lSun/apex-plugin-apexscreencapture#1]
Dear Daniel,

This plugin is very very useful. I am seeking a method to help user to easily submit SR in APEX application. 

I want to know if it is possible to capture partial area by user choose, e.g. user uses mouse to select a region then the plugin automatically capture this partial area of page?

Any idea is also appreciate!!

Thank you for sharing and have a nice day.

Best Regards,
Kenny Wang

**Comment by Dani3lSun** [comment]
Hi Kenny,

I think I know what you want and I´m currently working on a solution that a user can select a DIV and then generates the PNG only for that selected area, but it is in development right now, fyi I want to use this framework (jQuery.DomOutline):
http://rafaelcastrocouto.github.io/jQuery.DomOutline/demo/

For now you can get a similar solution (without the GUI candy:)) with a dynamic action:
1) Event: On Click --> Selection Type: Region --> Your region
2) Action: APEX screen capture: with JQuery Selector #REGION_STATIC_ID
See the screenshots!

Best Regards
Daniel

edit: Demo is online on: https://apex.oracle.com/pls/apex/f?p=57743:14
Just click somewhere in the second IR (User Objects) region...

<img width="291" alt="screen_01" src="https://cloud.githubusercontent.com/assets/698942/12038315/563f0f50-ae57-11e5-863e-e40eb77d7f23.png">
<img width="290" alt="screen_02" src="https://cloud.githubusercontent.com/assets/698942/12038320/5c46d356-ae57-11e5-8562-d2ffdaf1a434.png">

**Comment by Dani3lSun** [comment]
Hi Kenny,

was faster than I could think of!:) Hope you enjoy the new version. If you find any issue just open one up here on Github!;)

Regards
Daniel
