### ISSUE TITLE
screenshot with horizontal scroll

### ISSUE THREAD

**Issue by vinodnegi87** [Dani3lSun/apex-plugin-apexscreencapture#4]
*_Question *_
I downloaded your  screenshot plugin  and i want to take the screenshot of a page with horizontal scrolls in it. The plugin works fine with vertical scrolls  but it doesn't take the screen shot of the part which is not visible in the horizontal scroll. 

Can you please provide a solution for it?
Thanks in advance.

**Comment by Dani3lSun** [comment]
Hi @vinodnegi87 
I looked into that behavior and it seems that it is not possible without changing the html of your page. This plugin uses html2canvas for taking a screenshot of the page as it is. I found these issues on the github page of html2canvas:
https://github.com/niklasvh/html2canvas/issues/60
https://github.com/niklasvh/html2canvas/issues/108

The only way to solve it is to modify the html via a dynamic action just before the screenshot happens. I think you have to test it, the css style overflow:hidden should be changed to overflow:visible of the region.(maybe on multiple places).
I would test it with chrome developer tools or similar tool to get the result you would like to have, if that works write a javascript dynamic action to do the same changes you did with the developer tools...

Hope that helps!
