### ISSUE TITLE
Getting shadow while taking a screenshot

### ISSUE THREAD

**Issue by vinodnegi87** [Dani3lSun/apex-plugin-apexscreencapture#5]
Hi Dani,
while taking the screenshot, i was getting shadow in it. Can you please suggest something here so that i can remove the shadow from the chart.I have attached the screenshot for your help.
Any suggestion is helpful.
I have tried different colors, black color in the legend is something which is very blurred and that is color i need in the y- axis as well. 
Any suggestion here will be greatly appreciated.
Thanks.

![image](https://cloud.githubusercontent.com/assets/18333267/14466035/29fad886-00a3-11e6-8f4a-78be2cbbb163.png)

**Comment by Dani3lSun** [comment]
similar issue like #4
