### ISSUE TITLE
save signature in DB

### ISSUE THREAD

**Issue by ehabwagdy** [Dani3lSun/apex-plugin-apexscreencapture#7]
### Expected behavior

save the signature in DB 
### Actual behavior

1- what i should to write in "Save Button JQuery Selector" are button name or in button action select defined by dynamic action or what ?
2- i would to make change in attribute plsql to add my table are replace the following part 

IF NOT
      apex_collection.collection_exists(p_collection_name => l_collection_name) THEN
    apex_collection.create_collection(l_collection_name);
  END IF;
  -- add collection member (only if BLOB not null)
  IF dbms_lob.getlength(lob_loc => l_blob) IS NOT NULL THEN
    apex_collection.add_member(p_collection_name => l_collection_name,
                               p_c001            => l_filename, -- filename
                               p_c002            => l_mime_type, -- mime_type
                               p_d001            => SYSDATE, -- date created
                               p_blob001         => l_blob); -- BLOB img content
  END IF;

**with my table**
INSERT INTO CC.IBS_EMP_SIGNATURE (
   IBS_NO, EMP_SIGNATURE, BOSTA_ID) 
VALUES ( 44433/\* IBS_NO _/,
 l_blob/_ EMP_SIGNATURE _/,
4455 /_ BOSTA_ID */ );
commit;

**Comment by Dani3lSun** [comment]
Hi @ehabwagdy 
sorry I sent you the wrong issue link, here we are at the screen capture plugin...I will recreate this issue in the right place at the signature plugin site!

**Comment by Dani3lSun** [comment]
https://github.com/Dani3lSun/apex-plugin-apexsignature/issues/1

**Comment by ehabwagdy** [comment]
thanks for your support i will try and back to you

**Comment by ehabwagdy** [comment]
thanks a lot for your support and your effective plugin
and it's from my pleasure to communicate with you and if you want any
support in pl sql , forms ,report , ADF , OAF or EBS i am with you.
https://github.com/ehabwagdy

many thanks
ehab wagdy
002 01224031342
